name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  APP_DIR: /home/runner/BookMyTurf
  APP_NAME: book-my-turf

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        run: |
          cd $APP_DIR
          git pull origin main
          npm install

          pm2 describe $APP_NAME > /dev/null \
            && pm2 reload $APP_NAME \
            || pm2 start npm --name $APP_NAME -- start

          pm2 save